### ISSUE TITLE
2.0.72 release has wrong version in version.txt

### ISSUE THREAD

**Issue by patsoffice** [netbootxyz/netboot.xyz#1294]
**Describe the bug**
The 2.0.72 release includes the version.txt file for 2.0.73

**To Reproduce**
1. See https://github.com/netbootxyz/netboot.xyz/blob/2.0.72/version.txt

**Expected behavior**
The 2.0.72 release should not include commit https://github.com/netbootxyz/netboot.xyz/commit/585baf217ea746b16104c7d00c5635d333f1f089.

**Additional context**
This is not a huge issue, but my automation will automatically download the 2.0.72 release when it's already installed.

**Comment by Wolf1098** [comment]
I am not sure if this is the same bug, but ubuntu on 2.0.72 for amd64 has ubuntu using a commit/release that doesn't have a filesystem.squashfs and I am assuming is a commit cause it doesn't seem to show up in the list of releases for me, but the initrd does exist...

**Comment by realizelol** [comment]
Yes I also think that this will break releases info.

For example I can't download these debian-squash images:
```
rescatux
gparted-stable
grml-full
kali-xfce-squash
clonezilla-debian-stable-amd64
```
which will result in a 404:
```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: Response status was 404
    at ClientRequest.<anonymous> (/app/node_modules/node-downloader-helper/dist/index.js:1:9499)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
    at TLSSocket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
Emitted 'error' event on b instance at:
    at ClientRequest.<anonymous> (/app/node_modules/node-downloader-helper/dist/index.js:1:9630)
    at Object.onceWrapper (node:events:629:26)
    [... lines matching original stack trace ...]
    at Readable.push (node:internal/streams/readable:234:10) {
  status: 404,
  body: ''
}
```

The files from endpoints aren't available. Trying to download in "normal way" via web browser will also result in 404:
```
# grml-full
https://github.com/netbootxyz/debian-squash/releases/download/2022.11-af4f2941/filesystem.squashfs
https://github.com/netbootxyz/debian-squash/releases/download/2022.11-af4f2941/initrd
https://github.com/netbootxyz/debian-squash/releases/download/2022.11-af4f2941/vmlinuz
```
The commit is not found in the debian-squash repo releases:
https://github.com/netbootxyz/debian-squash/releases?q=%22af4f2941%22&expanded=true

<br/>

best regards

realizelol
